# Generated by Django 4.2 on 2023-04-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рекламные кампании')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткая ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Обозначение')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID чата клиента')),
                ('nickname', models.CharField(max_length=500, verbose_name='Никнейм клиента')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя клиента')),
                ('tel_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на ОПД')),
                ('personal_data_consent_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата согласия на ОПД')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название статуса доставки')),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тип доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название склада')),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('start_storage_date', models.DateField(auto_now_add=True, null=True, verbose_name='Открыто')),
                ('end_storage_date', models.DateField(blank=True, null=True, verbose_name='Закрыто')),
                ('paid_up_to', models.DateField(blank=True, null=True, verbose_name='Оплачено до')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('things', models.TextField(blank=True, max_length=50, null=True, verbose_name='Список вещей')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название заказа')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.box', verbose_name='Бокс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_at', models.DateTimeField(blank=True, null=True, verbose_name='Забрать в')),
                ('took_at', models.DateTimeField(blank=True, null=True, verbose_name='Забрали в')),
                ('deliver_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставить в')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставили в')),
                ('need_measurement', models.BooleanField(verbose_name='Требуются замеры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot.order', verbose_name='Заказ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot.deliverystatus', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.deliverytype', verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='bot.storage', verbose_name='Склад'),
        ),
    ]
