# Generated by Django 4.2 on 2023-04-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Обозначение')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='BoxUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Открыто')),
                ('end_date', models.DateField(verbose_name='Закрыто')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bot.box', verbose_name='Номер бокса')),
            ],
        ),
        migrations.CreateModel(
            name='BoxUsageByOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.boxusage')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название статуса доставки')),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название склада')),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Адрес склада',
                'verbose_name_plural': 'Адреса складов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID чата клиента')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя пользователя')),
                ('tel_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на ОПД')),
                ('personal_data_consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на ОПД')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='bot.user', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиентов',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_days', models.IntegerField(verbose_name='Количество оплаченных дней')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата фиксации')),
                ('box_usage_by_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.boxusagebyorders', verbose_name='Предмет платежа')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('box_usages', models.ManyToManyField(related_name='orders', through='bot.BoxUsageByOrders', to='bot.boxusage', verbose_name='Используемые боксы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.user', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'на хранение'), ('out', 'с хранения')], max_length=10, verbose_name='Тип доставки')),
                ('take_at', models.DateTimeField(blank=True, null=True, verbose_name='Забрать в')),
                ('took_at', models.DateTimeField(blank=True, null=True, verbose_name='Забрали в')),
                ('deliver_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставить в')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставили в')),
                ('need_measurement', models.BooleanField(verbose_name='Требуются замеры')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot.useraddress', verbose_name='Адрес доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot.order', verbose_name='Заказ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot.deliverystatus', verbose_name='Статус')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot.storage', verbose_name='Адрес склада')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.AddField(
            model_name='boxusagebyorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.order'),
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='bot.storage', verbose_name='Склад'),
        ),
    ]
