# Generated by Django 4.2 on 2023-04-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Рекламные кампании')),
                ('url', models.CharField(max_length=100, verbose_name='Короткая ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тип доставки')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.deliverytype', verbose_name='Тип доставки'),
        ),
    ]
